#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 24 14:26:28 2018

@author: dvg27
"""
import networkx as nx
import random
G = nx.planted_partition_graph(5, 100, 0.18, 0.0001, seed=42)
for v in G.nodes():
   G.node[v]['weight']=random.randint(1,10)   
n=G.number_of_nodes()
m=G.number_of_edges()
mx=max(nx.degree(G))[1]
print(n,m,nx.number_connected_components(G), mx)

nx.write_gexf(G, "lp2.gexf")
G = nx.planted_partition_graph(5, 300, 0.06, 0.0003, seed=12)
for v in G.nodes():
   G.node[v]['weight']=random.randint(0,10)
n=G.number_of_nodes()
m=G.number_of_edges()
mx=max(nx.degree(G))[1]
print(n,m, nx.number_connected_components(G), mx)

nx.write_gexf(G, "lp3.gexf")
G = nx.planted_partition_graph(5, 300, 0.06, 0.0003, seed=30)
for v in G.nodes():
   G.node[v]['weight']=random.randint(1,10)
    
n=G.number_of_nodes()
m=G.number_of_edges()
mx=max(nx.degree(G))[1]
print(n,m, nx.number_connected_components(G),mx )
nx.write_gexf(G, "lp1.gexf")